services:
  postgres:
    image: postgres:18
    container_name: orchestrator-integration-postgres
    environment:
      POSTGRES_DB: orchestrator_test
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD: orchestrator
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - integration_postgres_data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  integration_postgres_data:
