services:
  postgres:
    image: postgres:18
    container_name: orchestrator-postgres
    ports:
      - "10069:5432"
    environment:
      POSTGRES_DB: orchestrator
      POSTGRES_USER: orchestrator
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_db_password
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    secrets:
      - postgres_db_password

volumes:
  postgres_data:

secrets:
  postgres_db_password:
    file: ./secrets/postgres_db_password.txt
